%% define geometry
%tapping locations...
tapLcn = [...
    %X, Y, Z
    20, 0, 0;...
    -38, 0, 0;...
    -70.5, 0, 0;...
    -86.5, 28, 0;...
    -86.5, 0, -17.5;...
    -86.5, -28, 0;...
    20, 0, 0;...
    -38, 0, 0;...
    -70.5, 0, 0;...
    -86.5, 28, 0;...
    -86.5, 0, -17.5;...
    -86.5, -28, 0];

%names for tapping locations....must have the same number of entries as
%rows in expr.tapLcn
tapLcn_ID = {'C1_v', 'C2_v', 'C3_v', 'R1_v', 'V_v', 'R2_v',...
    'C1_h', 'C2_h', 'C3_h', 'R1_h', 'V_h', 'R2_h'};

%tapping directions.....must have the same number of rows as
%rows in expr.tapLcn
tapDir = [...
    %I, J, K
    0, 0, 1;... % direction for location #1
    0, 0, 1;... % direction for location #2,... each row gives [i,j,k] 
    0, 0, 1;...
    0, 0, 1;...
    0, 0, 1;...
    0, 0, 1;...
    0, 1, 0;... % direction for location #1
    0, 1, 0;... % direction for location #2,... each row gives [i,j,k] 
    0, 1, 0;...
    0, 1, 0;...
    0, 1, 0;...
    0, -1, 0];

%% setup parameter object
globObj = gvt.daq.Params(tapLcn,tapLcn_ID,tapDir);

globObj.SampleRate = 2000; %[Hz]
globObj.CollectionPeriod = 15; %collection period

%sensor configurations...  % FIRST CHANNEL MUST BE HAMMER FOR POST PROC TOOL
globObj.inptNum = 3; %number of input signals...
globObj.inptTags = {'Hammer', 'OOP', 'IP'};
globObj.chans = {'ai0', 'ai2', 'ai3'}; %input channels..
globObj.inptPlotClr = {'k', 'b', 'r'}; %signal plot colors....

%acquisition type: trigger settings..
globObj.Trig = gvt.daq.Trig("Hammer");
globObj.Trig.Threshold = 0.002; %threshold exceed condition
globObj.Trig.Buffer = 0.1; %collection initialised at t=trigger time - buffer

%% Run the GVT GUI
globObj.StartUI();